print ("       X^Y")
print ("")
print ("4 Power 2  =>  4**2")
print ("     ",4**2)
print ("")
print ("5 Power 2  =>  5**2")
print ("     ",5**2)
print ("")
print ("6 Power 2  =>  6**2")
print ("     ",6**2)
print ("")
